### ISSUE TITLE
问问题，却回复了歌单

### ISSUE THREAD

**Issue by DY56GO** [liyupi/yucongming-java-sdk#10]
使用SDK回答问题，有些时候特别倾向于回答歌单，就是答非所问，如下，我提问“一个后台管理系统通用的功能有哪些？”，直接回复了歌单，但是偶尔会回复正确，在鱼聪明平台上提问就没有这种回复歌单的问题。
`
message: 一个后台管理系统通用的功能有哪些？
answer: 播放清单名称：Sunset Vibes

播放清单描述：在这个播放清单中，我为你精选了一些与给定歌曲相似的轻柔、悠扬的歌曲，让你感受到日落时分最美妙的氛围。

播放清单歌曲：

1. "Photograph" - Ed Sheeran
2. "Say You Won't Let Go" - James Arthur
3. "A Thousand Years" - Christina Perri
4. "Lucky" - Jason Mraz ft. Colbie Caillat
5. "Like I'm Gonna Lose You" - Meghan Trainor ft. John Legend
6. "Hallelujah" - Leonard Cohen
7. "Home" - Edward Sharpe & The Magnetic Zeros
8. "Ho Hey" - The Lumineers
9. "Lost Stars" - Adam Levine
10. "The A Team" - Ed Sheeran
`

**Comment by luoye6** [comment]
+1

**Comment by DY56GO** [comment]
问题已经解决，在后面的BI项目中有提到，这个模型是可以选择的，在SDK中提供的就是一个歌单的对话助手模型，你可以在平台上创建你要的助手（在左边搜索框的加号），创建好助手后，右边的“助手信息”中的id就是你想要的模型id，复制到SDK中就可以了，在平台上还可以进行高级设置，设置关联历史消息数，回复最大词数等。

**Comment by luoye6** [comment]
鱼皮哥找不到助手信息中的模型id，如何是好




落叶无情
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyupi/yucongming-java-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liyupi/yucongming-java-sdk] 问问题，却回复了歌单 (Issue #10)





 
问题已经解决，在后面的BI项目中有提到，这个模型是可以选择的，在SDK中提供的就是一个歌单的对话助手模型，你可以在平台上创建你要的助手（在左边搜索框的加号），创建好助手后，右边的“助手信息”中的id就是你想要的模型id，复制到SDK中就可以了，在平台上还可以进行高级设置，设置关联历史消息数，回复最大词数等。

**Comment by DY56GO** [comment]
好像鱼聪明AI助手不行，没有id，我创建的是一个编程的助手，里面就有。

**Comment by luoye6** [comment]
我创建的好像都没有，是权限问题吗，可我是会员，再高一级就是管理员，不知道其他人有没有这个问题，是BUG还是什么问题


落叶无情
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyupi/yucongming-java-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liyupi/yucongming-java-sdk] 问问题，却回复了歌单 (Issue #10)





 
好像鱼聪明AI助手不行，没有id，我创建的是一个编程的助手，里面就有。

**Comment by liyupi** [comment]
主页 => 我的助手 => 点击助手卡片的 “三个点” 进入助手详情页

**Comment by DY56GO** [comment]
我又去研究了一下，左边搜索框旁边的加号是创建对话，那里创建的不是助手，创建助手在是首页（蓝色）“做你强大的AI助手”标题下面的那个“创建助手”，创建后在点击（蓝色）下面“我的助手”就可看见了
