### ISSUE TITLE
一直模型Id不存在。

### ISSUE THREAD

**Issue by AnAloneJaver** [liyupi/yucongming-java-sdk#2]
模型id是不是在地址栏中的最后一个参数？
https://www.yucongming.com/chat/1658553107057070081
如果地址栏中是这个的话，那么模型id是否为1658553107057070081
测试了几个模型id都不存在。不知道为啥

**Comment by AnAloneJaver** [comment]
但是，我扒拉yucongming的源码找到了一个能用的modelId。

**Comment by liyupi** [comment]
你填写的是会话 id，模型 id 可以从模型的分享链接中拿到，后面我们优化下获取方式

**Comment by AnAloneJaver** [comment]
非常感谢您，通过分享链接已经拿到了模型id。
btw，如果我按照示例接入，我发现从我请求到yucongming返回，时间非常长，我猜测是yucongming给我用流式返回内容了，这里我想再我自己的前端输入问题，请求到我的后台，然后我的后台再去请求yucongming，如何给yucongming流式返回的内容直接返回到我的前端呢？能否给一个示例的代码呢，非常感谢鱼老板。

**Comment by liyupi** [comment]
不是流式返回的原因哈，我们现在只提供了生成好内容才返回的接口（而不是流式接口），生成是需要一定时间的。短期内估计无法支持流式，等系统稳定了我们再考虑开放哈
